### ISSUE TITLE
Release without a download throw exception

### ISSUE THREAD

**Issue by sixty4k** [Ezwen/bandcamp-collection-downloader#4]
Exception:
```
Exception in thread "pool-1-thread-3" java.lang.NullPointerException
        at bandcampcollectiondownloader.BandcampAPIConnector.retrieveRealDownloadURL(BandcampAPIConnector.kt:177)
        at bandcampcollectiondownloader.BandcampCollectionDownloader.manageDownloadPage(BandcampCollectionDownloader.kt:133)
        at bandcampcollectiondownloader.BandcampCollectionDownloader.access$manageDownloadPage(BandcampCollectionDownloader.kt:13)
        at bandcampcollectiondownloader.BandcampCollectionDownloader$downloadAll$task$1.run(BandcampCollectionDownloader.kt:87)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:830)
Exception in thread "pool-1-thread-5" java.lang.NullPointerException
        at bandcampcollectiondownloader.BandcampAPIConnector.retrieveRealDownloadURL(BandcampAPIConnector.kt:177)
        at bandcampcollectiondownloader.BandcampCollectionDownloader.manageDownloadPage(BandcampCollectionDownloader.kt:133)
        at bandcampcollectiondownloader.BandcampCollectionDownloader.access$manageDownloadPage(BandcampCollectionDownloader.kt:13)
        at bandcampcollectiondownloader.BandcampCollectionDownloader$downloadAll$task$1.run(BandcampCollectionDownloader.kt:87)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:830)
```

Example release: 
https://medicalrecords.bandcamp.com/album/helium-mr-052

There does seem to be logic to deal with this, but somehow we’re not hitting it.

btw, this project has been a great help to my attempting to sync all of my music, thank you for making it public!

**Comment by Ezwen** [comment]
Hi there! Sorry for answering a little late. I've tried a fix in my latest commit. If you have time could you try the following test build, and tell me if that solved the problem? https://framagit.org/Ezwen/bandcamp-collection-downloader/-/jobs/1093277/artifacts/raw/build/libs/bandcamp-collection-downloader.jar?inline=false

**Comment by Ezwen** [comment]
I believe this is fixed, if there is a problem again please do not hesitate to reopen.
