### ISSUE TITLE
Fails to download album with quotes in the title?

### ISSUE THREAD

**Issue by cmdcolin** [Ezwen/bandcamp-collection-downloader#6]
Example https://norentrecords.bandcamp.com/album/fragmented-warehouse-nrr105
The error is maybe filesystem related
Produces this error

```
[pool-1-thread-1] Error while trying: "java.nio.file.FileSystemException: /media/cdiesh/SEAGATE BAC/./Bandcamp/Sterile Garden/2019 - "Fragmented Warehouse" (NRR105): Invalid argument".
[pool-1-thread-1] Retrying (1/3).
[pool-1-thread-1] Error while trying: "java.nio.file.FileSystemException: /media/cdiesh/SEAGATE BAC/./Bandcamp/Sterile Garden/2019 - "Fragmented Warehouse" (NRR105): Invalid argument".
[pool-1-thread-1] Retrying (2/3).
[pool-1-thread-1] Error while trying: "java.nio.file.FileSystemException: /media/cdiesh/SEAGATE BAC/./Bandcamp/Sterile Garden/2019 - "Fragmented Warehouse" (NRR105): Invalid argument".
[pool-1-thread-1] Retrying (3/3).
[pool-1-thread-1] Error while trying: "java.nio.file.FileSystemException: /media/cdiesh/SEAGATE BAC/./Bandcamp/Sterile Garden/2019 - "Fragmented Warehouse" (NRR105): Invalid argument".
Exception in thread "pool-1-thread-1" [pool-1-thread-5] Managing item 50/1480                                                                                
bandcampcollectiondownloader.BandCampDownloaderError: Could not perform task after 3 retries.
        at bandcampcollectiondownloader.Util.retry(Util.kt:168)
        at bandcampcollectiondownloader.BandcampCollectionDownloader.manageDownloadPage(BandcampCollectionDownloader.kt:149)
        at bandcampcollectiondownloader.BandcampCollectionDownloader.access$manageDownloadPage(BandcampCollectionDownloader.kt:13)
        at bandcampcollectiondownloader.BandcampCollectionDownloader$downloadAll$task$1.run(BandcampCollectionDownloader.kt:87)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:832)

```

**Comment by cmdcolin** [comment]
Possibly also with question mark in title

```
[pool-1-thread-5] Starting the download of "It Never Ends, Does It?" by Dysthymia.
[pool-1-thread-5] Error while trying: "java.nio.file.FileSystemException: /media/cdiesh/SEAGATE BAC/./Bandcamp/Dysthymia/2019 - It Never Ends, Does It?: Invalid argument".
[pool-1-thread-5] Retrying (1/3).
[pool-1-thread-5] Error while trying: "java.nio.file.FileSystemException: /media/cdiesh/SEAGATE BAC/./Bandcamp/Dysthymia/2019 - It Never Ends, Does It?: Invalid argument".
[pool-1-thread-5] Retrying (2/3).
[pool-1-thread-5] Error while trying: "java.nio.file.FileSystemException: /media/cdiesh/SEAGATE BAC/./Bandcamp/Dysthymia/2019 - It Never Ends, Does It?: Invalid argument".
[pool-1-thread-5] Retrying (3/3).
[pool-1-thread-5] Error while trying: "java.nio.file.FileSystemException: /media/cdiesh/SEAGATE BAC/./Bandcamp/Dysthymia/2019 - It Never Ends, Does It?: Invalid argument".
Exception in thread "pool-1-thread-5" bandcampcollectiondownloader.BandCampDownloaderError: Could not perform task after 3 retries.
[pool-1-thread-7] Managing item 145/1480
        at bandcampcollectiondownloader.Util.retry(Util.kt:168)
        at bandcampcollectiondownloader.BandcampCollectionDownloader.manageDownloadPage(BandcampCollectionDownloader.kt:149)
        at bandcampcollectiondownloader.BandcampCollectionDownloader.access$manageDownloadPage(BandcampCollectionDownloader.kt:13)
        at bandcampcollectiondownloader.BandcampCollectionDownloader$downloadAll$task$1.run(BandcampCollectionDownloader.kt:87)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)

```

**Comment by Ezwen** [comment]
Thanks for the report! What OS are you using?

**Comment by Ezwen** [comment]
I already have a place in the code where I replace invalid characters by unicode characters that look alike, I suppose when I have time I can simply add a few more to cover your case: https://github.com/Ezwen/bandcamp-collection-downloader/blob/df44dda6f596817a29990d08ee6268b9157b2e23/src/main/kotlin/bandcampcollectiondownloader/Util.kt#L124

of course if you'd like to make the change yourself, PRs are very welcome :)

**Comment by cmdcolin** [comment]
Thanks for sure...I am on ubuntu right now. I am super happy to have this running and I think I am setup to make PR changes if I get a chance :)

**Comment by cmdcolin** [comment]
Ubuntu 20.04 to be precise

**Comment by cmdcolin** [comment]
Just to keep track of other things I think vertical bar also causes trouble

 Found release "Ceramic Tigers" by | RG |.
```
[pool-1-thread-5] Error while trying: "java.nio.file.FileSystemException: /media/cdiesh/SEAGATE BAC/./Bandcamp/| RG |: Invalid argument".
Exception in thread "pool-1-thread-5" bandcampcollectiondownloader.BandCampDownloaderError: Could not perform task after 3 retries.
[pool-1-thread-10] Managing item 130/1271
        at bandcampcollectiondownloader.Util.retry(Util.kt:168)
        at bandcampcollectiondownloader.BandcampCollectionDownloader.manageDownloadPage(BandcampCollectionDownloader.kt:149)
        at bandcampcollectiondownloader.BandcampCollectionDownloader.access$manageDownloadPage(BandcampCollectionDownloader.kt:13)
        at bandcampcollectiondownloader.BandcampCollectionDownloader$downloadAll$task$1.run(BandcampCollectionDownloader.kt:87)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:832)

```

**Comment by Ezwen** [comment]
Thanks for the additional information. I have tried to fix all similar problems with my latest commit (https://github.com/Ezwen/bandcamp-collection-downloader/commit/4445302ab487786ac4d4f7782ab0632722e441f3).

Can you try this build to see if it solves your problems? 
https://framagit.org/Ezwen/bandcamp-collection-downloader/-/jobs/1059360/artifacts/raw/build/libs/bandcamp-collection-downloader.jar?inline=false

**Comment by Ezwen** [comment]
Any news? The build link I provided above has been deleted, but I triggered a new build here: https://framagit.org/Ezwen/bandcamp-collection-downloader/-/jobs/1093273/artifacts/raw/build/libs/bandcamp-collection-downloader.jar?inline=false

**Comment by cmdcolin** [comment]
Awesome, it appears to download the items with quotes now, and I used the provided framagit jar above!

**Comment by cmdcolin** [comment]
Even the vertical bars one, very impressive :)

Thanks so much

**Comment by Ezwen** [comment]
Great! Thanks for testing!
